services:
  db:
    image: neo4j:5-community
    container_name: nsql_anim_db
    environment:
      NEO4J_AUTH: ${NEO4J_AUTH}
      NEO4J_PLUGINS: '["apoc"]'
      NEO4J_apoc_export_file_enabled: "true"
      NEO4J_apoc_import_file_enabled: "true"

    volumes:
      - neo4j_data:/data
      - neo4j_import:/import:ro
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "${NEO4J_PASSWORD}", "RETURN 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: nsql_anim_backend
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
    - ./backend/backups:/app/backups
    ports:
      - "127.0.0.1:8000:8000"
    restart: unless-stopped
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: nsql_anim_frontend
    depends_on:
      - backend
    ports:
      - "127.0.0.1:5173:80"
    restart: unless-stopped

volumes:
  neo4j_data:
  neo4j_import: