services:
  db:
    image: neo4j:5-community
    environment:
      NEO4J_AUTH: ${NEO4J_AUTH}
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./backend/storage:/data
  
  backend:
    image: ghcr.io/astral-sh/uv:debian-slim
    tty: true
    working_dir: /app
    volumes:
      - ./backend:/app
    env_file:
      - .env
    entrypoint: ["uv", "run", "./src/main.py"]
    depends_on:
      db:
        condition: service_started
    ports:
      - "${APP_PORT}:${APP_PORT}"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.frontend
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    ports:
      - "5173:5173"
